<div class="pr-report pro-band-dash">
<header class="pr-top"><div class="pr-top__inner"><span class="logo rp-top__logo"><span class="logo__icon" aria-hidden="true"><svg viewBox="13 8.5 52 52" focusable="false"><path fill="currentColor" fill-rule="evenodd" d="M62 30 L58 28.5 L40 20 L35 17.5 L28 12 L21 15.5 Q13 32 17 57 L32 57 Q28.5 46.5 37 41 L39 38 L58 34.5 L61 32.5 Z M27.5 16.5 L16 25 L27 22.5 Z M38.4 22.9 a1.6 1.6 0 1 0 3.2 0 a1.6 1.6 0 1 0 -3.2 0 Z"/></svg></span><span class="logo__mark">Citehound</span></span><span class="pr-top__label">Sample report</span></div></header>
<nav class="pr-nav" aria-label="Report sections"><ul><li><span>Summary</span></li><li><span>Pillars</span></li><li><span aria-current="true">Pages</span></li><li><span>Estimated score</span></li></ul></nav><div class="pro-band-dash__body"><div class="pr-tablewrap"><table class="pr-table pr-table--pages"><caption class="pr-vh">Pages</caption><thead role="rowgroup"><tr role="row"><th scope="col" role="columnheader" aria-sort="ascending" data-sort="path">Page</th><th scope="col" role="columnheader" class="pr-num" data-sort="score">Score</th><th scope="col" role="columnheader" class="pr-num" data-sort="failed">Failed checks</th><th scope="col" role="columnheader">What failed</th></tr></thead><tbody>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">87</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">0</span></td><td role="cell" data-label="What failed"><span class="pr-muted">No page-level check fails.</span></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/about</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/agentic-commerce</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">87</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">0</span></td><td role="cell" data-label="What failed"><span class="pr-muted">No page-level check fails.</span></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">77</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">2</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>2 failed checks</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li><li><strong>Subheading structure (H2)</strong> <span class="pr-muted">0/5</span><br />Break content into H2 sections</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks/consumer-apps</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks/crm</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks/cybersecurity</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks/devtools</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
</tbody></table></div></div>
</div>
