<div class="pr-report">
<section class="pr-pillarblock" data-pillar="tech">
<div class="pr-pillarblock__head"><h4 class="pr-h4">Technical foundation</h4><p class="pr-pillarblock__score"><strong>20</strong> / 20</p></div>
<p class="pr-note">The tags and markup that tell a machine what each page is.</p>
<div class="pr-tablewrap"><table class="pr-table pr-table--checks" role="table"><caption class="pr-vh">Technical foundation: every check</caption><thead role="rowgroup"><tr role="row"><th scope="col" role="columnheader">Check</th><th scope="col" role="columnheader">Result</th><th scope="col" role="columnheader" class="pr-num">Points</th><th scope="col" role="columnheader">What to change</th></tr></thead><tbody role="rowgroup">
<tr role="row" class="is-pass"><th scope="row" role="rowheader" data-label="Check">Canonical tag</th><td role="cell" data-label="Result"><span class="pr-state pr-state--pass">Pass</span> Passes on all 28 pages</td><td role="cell" class="pr-num" data-label="Points">4</td><td role="cell" data-label="What to change"><span class="pr-muted">Nothing to change.</span></td></tr>
<tr role="row" class="is-pass"><th scope="row" role="rowheader" data-label="Check">html lang attribute</th><td role="cell" data-label="Result"><span class="pr-state pr-state--pass">Pass</span> Passes on all 28 pages</td><td role="cell" class="pr-num" data-label="Points">3</td><td role="cell" data-label="What to change"><span class="pr-muted">Nothing to change.</span></td></tr>
<tr role="row" class="is-pass"><th scope="row" role="rowheader" data-label="Check">Meta description</th><td role="cell" data-label="Result"><span class="pr-state pr-state--pass">Pass</span> Passes on all 28 pages</td><td role="cell" class="pr-num" data-label="Points">4</td><td role="cell" data-label="What to change"><span class="pr-muted">Nothing to change.</span></td></tr>
<tr role="row" class="is-pass"><th scope="row" role="rowheader" data-label="Check">Open Graph tags</th><td role="cell" data-label="Result"><span class="pr-state pr-state--pass">Pass</span> Passes on all 28 pages</td><td role="cell" class="pr-num" data-label="Points">3</td><td role="cell" data-label="What to change"><span class="pr-muted">Nothing to change.</span></td></tr>
<tr role="row" class="is-fail"><th scope="row" role="rowheader" data-label="Check">Page title</th><td role="cell" data-label="Result"><span class="pr-state pr-state--fail">Fail</span> Fails on <span data-fig="pr-check-failing">1</span> of 28 pages<span class="rp-bar rp-bar--risk" aria-hidden="true"><span class="rp-bar__fill" style="width:4%"></span></span></td><td role="cell" class="pr-num" data-label="Points">3</td><td role="cell" data-label="What to change">Write a descriptive 10–70 character title<br /><span class="pr-muted">Answer engines frequently use the title as your source label.</span></td></tr>
<tr role="row" class="is-pass"><th scope="row" role="rowheader" data-label="Check">Structured data (JSON-LD)</th><td role="cell" data-label="Result"><span class="pr-state pr-state--pass">Pass</span> Passes on all 28 pages</td><td role="cell" class="pr-num" data-label="Points">3</td><td role="cell" data-label="What to change"><span class="pr-muted">Nothing to change.</span></td></tr>
</tbody></table></div>
</section>
</div>
