<div class="rp-report rp-js">
<div class="rp-matrixwrap"><table class="rp-matrix">
<thead><tr><th scope="col" class="rp-matrix__corner">Page</th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">Canonical</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">Language</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">Title</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">Description</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">Open Graph</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">JSON-LD</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">H1</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">H2</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">Org schema</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">Content schema</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">About</span></th><th scope="col" class="rp-colhead"><span class="rp-colhead__text">Contact</span></th></tr></thead>
<tbody class="rp-cluster"><tr class="rp-cluster__head"><th scope="rowgroup" colspan="13"><span class="rp-cluster__name">/benchmarks</span><span class="rp-cluster__meta">6 pages, average 82</span></th></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/benchmarks/consumer-apps</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/benchmarks/crm</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/benchmarks/cybersecurity</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/benchmarks/devtools</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/benchmarks/dtc-brands</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/benchmarks/hospitality</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
</tbody>
<tbody class="rp-cluster"><tr class="rp-cluster__head"><th scope="rowgroup" colspan="13"><span class="rp-cluster__name">/tools</span><span class="rp-cluster__meta">2 pages, average 87, no failing checks</span></th></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/tools/llms-txt-checker</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/tools/schema-generator</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
</tbody>
<tbody class="rp-cluster"><tr class="rp-cluster__head"><th scope="rowgroup" colspan="13"><span class="rp-cluster__name">/research</span><span class="rp-cluster__meta">1 page, average 76</span></th></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/research/case-study-agaone</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
</tbody>
<tbody class="rp-cluster"><tr class="rp-cluster__head"><th scope="rowgroup" colspan="13"><span class="rp-cluster__name">/benchmarks</span><span class="rp-cluster__meta">1 page, average 77</span></th></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/benchmarks</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
</tbody>
<tbody class="rp-cluster"><tr class="rp-cluster__head"><th scope="rowgroup" colspan="13"><span class="rp-cluster__name">/research</span><span class="rp-cluster__meta">1 page, average 77</span></th></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/research</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
</tbody>
<tbody class="rp-cluster"><tr class="rp-cluster__head"><th scope="rowgroup" colspan="13"><span class="rp-cluster__name">/tools</span><span class="rp-cluster__meta">1 page, average 77</span></th></tr>
<tr class="rp-matrix__row"><th scope="row"><span >/tools</span></th><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--fail" data-cell="fail"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td><td><span class="rp-cell rp-cell--pass" data-cell="pass"></span></td></tr>
</tbody>
</table></div>
</div>
