<div class="pr-report">
<div class="pr-tablewrap"><table class="pr-table pr-table--pages"><caption class="pr-vh">Pages</caption><thead role="rowgroup"><tr role="row"><th scope="col" role="columnheader" aria-sort="ascending" data-sort="path">Page</th><th scope="col" role="columnheader" class="pr-num" data-sort="score">Score</th><th scope="col" role="columnheader" class="pr-num" data-sort="failed">Failed checks</th><th scope="col" role="columnheader">What failed</th></tr></thead><tbody>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">87</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">0</span></td><td role="cell" data-label="What failed"><span class="pr-muted">No page-level check fails.</span></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/about</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/agentic-commerce</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">87</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">0</span></td><td role="cell" data-label="What failed"><span class="pr-muted">No page-level check fails.</span></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">77</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">2</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>2 failed checks</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li><li><strong>Subheading structure (H2)</strong> <span class="pr-muted">0/5</span><br />Break content into H2 sections</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks/consumer-apps</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks/crm</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks/cybersecurity</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
<tr role="row" class="pr-row" data-kind="ok"><th scope="row" role="rowheader" data-label="Page"><span >/benchmarks/devtools</span></th><td role="cell" class="pr-num" data-label="Score"><span data-fig="pr-page-score">82</span></td><td role="cell" class="pr-num" data-label="Failed checks"><span data-fig="pr-page-failed">1</span></td><td role="cell" data-label="What failed"><details class="pr-det"><summary>1 failed check</summary><ul class="pr-fails"><li><strong>Content schema (Article, FAQ…)</strong> <span class="pr-muted">0/5</span><br />Add Article or FAQPage schema</li></ul></details></td></tr>
</tbody></table></div>
</div>
